<?php
defined('_JEXEC') or 
    die('Direct Access to this location is not allowed');
?>
<div id="cpanel"><?php if($this->menuItems !== NULL) {
        foreach($this->menuItems as $menuItem) {
            $this->quickIcon( 
                    $menuItem['link'],
                    $menuItem['icon'],
                    $this->translate->_($menuItem['text'])
                );
        }
    }
?></div>